{
 "title": "NVMe Exporter",
 "description": "NVMe SSD Device Health Metrics (Lifetime, Temperature, Read/Write Operation Count, Critical Warning)",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(nvme_smart_log_temperature,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage Used by Device",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nvme_smart_log_percent_used", "legendFormat": "{{devno}}" }
   ]
  },
  {
   "title": "NVMe Ctrl",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_ctrl_cc{device=\"$device\",cc=\"en\"}"
    }
   ]
  },
  {
   "title": "Percent Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_percent_used{device=\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_temperature{device=\"$device\"} - 273.15",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "NVM Subsystem Reliability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_critical_warning{device=\"$device\",critical_warning=\"nvm_subsystem_reliability\"}"
    }
   ]
  },
  {
   "title": "Volatile Backup Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_critical_warning{device=\"$device\",critical_warning=\"volatile_backup_failed\"}"
    }
   ]
  },
  {
   "title": "Available Spare",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_critical_warning{device=\"$device\",critical_warning=\"avail_spare\"}"
    }
   ]
  },
  {
   "title": "Error Log Entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_num_error_log_entries{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "NVMe Ctrl",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_ctrl_csts{device=\"$device\",csts=\"rdy\"}"
    }
   ]
  },
  {
   "title": "Available Spare",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_avail_spare{device=\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Spare Threshold",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_spare_thresh{device=\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_critical_warning{device=\"$device\",critical_warning=\"read_only\"}"
    }
   ]
  },
  {
   "title": "Temperature Threshold",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_critical_warning{device=\"$device\",critical_warning=\"temp_threshold\"}"
    }
   ]
  },
  {
   "title": "Persistent Mem Read Only",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_critical_warning{device=\"$device\",critical_warning=\"persistent_memory_read_only\"}"
    }
   ]
  },
  {
   "title": "Media Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvme_smart_log_media_errors{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Power Cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvme_smart_log_power_cycles{device=\"$device\"}",
     "legendFormat": "Safe"
    },
    {
     "expr": "nvme_smart_log_unsafe_shutdowns{device=\"$device\"}",
     "legendFormat": "Unsafe"
    }
   ]
  },
  {
   "title": "Warning Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvme_smart_warning_temp_time{device=\"$device\"}",
     "legendFormat": "warning"
    },
    {
     "expr": "nvme_smart_critical_comp_time{device=\"$device\"}",
     "legendFormat": "critical"
    }
   ]
  },
  {
   "title": "Power on Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvme_smart_log_power_on_hours{device=\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Data Unit Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvme_smart_log_data_units_read{device=\"$device\"} * 512 * 1024 / 1024 / 1024 / 1024",
     "legendFormat": "Read"
    },
    {
     "expr": "nvme_smart_log_data_units_written{device=\"$device\"} * 512 * 1024 / 1024 / 1024 / 1024",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Host Command Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvme_smart_log_host_read_commands{device=\"$device\"} ",
     "legendFormat": "Read"
    },
    {
     "expr": "nvme_smart_log_host_write_commands{device=\"$device\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Controller Busy Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvme_smart_log_controller_busy_time{device=\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}