image:
  registry: docker.io
  repository: jlesage/jdownloader-2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  digest: null

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  port: 5800

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

networkPolicy:
  dnsSelector:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
  ingress: []

storage:
  config:
    existingPvc: null
    pvc:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
    volumeMount:
      subPath: null
  output:
    existingPvc: null
    pvc:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
    volumeMount:
      subPath: null

