apiVersion: v2
name: roundcube
description: Helm Chart for Roundcube
version: 0.0.1
appVersion: "1.7.1"
type: application

sources:
  - https://github.com/roundcube/roundcubemail-docker
  - https://github.com/pschichtel/helm-charts

keywords:
  - roundcube
  - roundcubemail
  - webmail
