{{- if not .Values.storage.existingPvcName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keycloak-backup.fullname" . }}
  labels:
    {{- include "keycloak-backup.labels" . | nindent 4 }}
    {{- with .Values.storage.spec.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.storage.spec.annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.storage.spec.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.spec.capacity }}
{{- end }}