{{- if .Values.adminIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.adminIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.adminIngress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- $hosts := list (index (regexSplit "/" (.Values.adminHostname | required "adminHostname must be set!") -1) 2) }}
  {{- $hosts = concat $hosts .Values.adminIngress.extraHosts }}
  rules:
    {{- range $host := $hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "keycloak.fullname" $ }}-service
                port:
                  name: http 
    {{- end }}
  {{- with .Values.adminIngress.tls }}
  tls: {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
