apiVersion: v2
name: dawarich
description: "Self-hosted alternative to Google Location History"
type: application
version: 0.3.3
# renovate: image=docker.io/freikin/dawarich
appVersion: "1.14.3"
sources:
  - https://dawarich.app
