
{{- define "roundcube.encryption" -}}
{{- if not (has . (list "none" "starttls" "ssltls")) -}}
{{ required (printf "invalid value for encryption: %s" .) nil -}}
{{- else if  eq . "starttls" -}}
tls://
{{- else if  eq . "ssltls" -}}
ssl://
{{- end -}}
{{- end -}}

{{- define "roundcube.plugins.list" -}}
{{- $pluginList := list -}}
{{- range $plugin, $settings := .Values.config.plugins -}}
{{- if $settings }}
{{- if $settings.enabled -}}
{{- $pluginList = append $pluginList $plugin -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- $pluginList | join "," -}}
{{- end -}}

{{- define "roundcube.skins.requirements" -}}
{{- $skinList := list -}}
{{- range $skin, $settings := .Values.config.skins -}}
{{- if $settings -}}
{{- if $settings.enabled -}}
{{- $composerPackage := printf "roundcube/%s" $skin -}}
{{- $composerVersion := $.Chart.AppVersion -}}
{{- if $settings.composerPackage -}}
{{- if $settings.composerPackage.name -}}
{{- $composerPackage = $settings.composerPackage.name -}}
{{- end -}}
{{- if $settings.composerPackage.version -}}
{{- $composerVersion = $settings.composerPackage.version -}}
{{- end -}}
{{- end -}}
{{- $skinRequirement := printf "%s:%s" $composerPackage $composerVersion -}}
{{- $skinList = append $skinList $skinRequirement -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- $skinList | join " " -}}
{{- end -}}

{{- define "roundcube.plugins.requirements" -}}
{{- $pluginList := list -}}
{{- range $plugin, $settings := .Values.config.plugins -}}
{{- if $settings }}
{{- if and $settings.enabled $settings.composerPackage -}}
{{- $pluginRequirement := "" -}}
{{- if $settings.composerPackage.version -}}
{{- $pluginRequirement = printf "%s:%s" $settings.composerPackage.name $settings.composerPackage.version -}}
{{- else -}}
{{- $pluginRequirement = $settings.composerPackage.name -}}
{{- end -}}
{{- $pluginList = append $pluginList $pluginRequirement -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- $pluginList | join "," -}}
{{- end -}}


{{- define "roundcube.deployment.command" -}}
{{- $hasPlugins := false }}
{{- range .Values.config.plugins }}
{{- if .enabled }}
{{- $hasPlugins = true }}
{{- end }}
{{- end }}
{{- if $hasPlugins -}}
(cd /usr/src/roundcubemail && composer require 'roundcube/plugin-installer:>=0.3.5') &&
{{ end }}/docker-entrypoint.sh php-fpm
{{- end -}}


{{- define "roundcube.helm2php" -}}
{{- $kind := kindOf . -}}
{{- if has $kind (list "slice" "map") -}}
json_decode({{- . | toJson | quote -}}, true)
{{- else if has $kind (list "string") -}}
{{- . | quote -}}
{{- else -}}
{{- . -}}
{{- end -}}
{{- end -}}

{{/*
Create the name of the service account to use
*/}}
{{- define "roundcube.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
{{ default (include "common.names.fullname" .) .Values.serviceAccount.name }}
{{- else -}}
{{ default "default" .Values.serviceAccount.name }}
{{- end -}}
{{- end -}}
