---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "roundcube.fullname" . }}
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
  {{- with .Values.ingress.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: {{ required "No ingress host defined" .Values.ingress.host }}
      http:
        paths:
          - path: {{ if not (eq .Values.ingress.path "/") }}{{ trimSuffix "/" .Values.ingress.path }}(/|$)(.*){{ else }}/{{ end }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "roundcube.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.useTLS }}
  tls:
    - hosts:
        - {{ required "No ingress host defined" .Values.ingress.host }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- else }}
      secretName: {{ include "roundcube.fullname" . }}-tls
      {{- end }}
  {{- end }}
{{- end -}}
