---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roundcube.fullname" . }}
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtpUsername: "{{ .Values.smtp.username }}"
  smtpPassword: "{{ .Values.smtp.password }}"
  dbUsername: "{{ .Values.externalDatabase.user }}"
  dbPassword: "{{ .Values.externalDatabase.password }}"
  {{- if kindIs "string" .Values.config.desKey }}
  desKey: "{{ .Values.config.desKey }}"
  {{- end }}
