apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dawarich.fullname" . }}
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dawarich.replicaCount }}
  selector:
    matchLabels:
      {{- include "dawarich.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/configmap: {{ ((include (print $.Template.BasePath "/configmap.yaml") $) | fromYaml).data | toYaml | sha256sum }}
        checksum/secret: {{ ((include (print $.Template.BasePath "/secret.yaml") $) | fromYaml).data | toYaml | sha256sum }}
      labels:
        {{- include "dawarich.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "dawarich.podSecurityContext" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.image }}
          {{- if .digest }}
          image: {{ print .registry "/" .repository "@" .digest | quote }}
          {{- else }}
          image: {{ print .registry "/" .repository ":" (.tag | default $.Chart.AppVersion) | quote }}
          {{- end }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          command: ['web-entrypoint.sh']
          args: ['bin/rails', 'server', '-p', '3000', '-b', '::']
          envFrom:
            {{- include "dawarich.envFrom" . | nindent 12 }}
          env:
            {{- include "dawarich.env" . | nindent 12 }}
            {{- if .Values.metrics.enabled }}
            - name: SIDEKIQ_METRICS_URL
              value: 'http://{{ include "dawarich.fullname" . }}-sidekiq:{{ include "dawarich.prometheusPort" . }}/metrics'
            {{- end }}
          {{- include "dawarich.securityContext" . | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- include "dawarich.livenessProbe" . | nindent 12 }}
          readinessProbe:
            {{- include "dawarich.readinessProbe" . | nindent 12 }}
          startupProbe:
            {{- include "dawarich.startupProbe" . | nindent 12 }}
          resources:
            {{- toYaml .Values.dawarich.resources | nindent 12 }}
          volumeMounts:
            {{- include "dawarich.volumeMounts" . | trim | nindent 12 }}
      volumes:
        {{- include "dawarich.volumes" . | trim | nindent 8 }}
      {{- with .Values.dawarich.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dawarich.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dawarich.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
