{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dawarich.fullname" . }}
spec:
  endpoints:
    - port: http
      scheme: http
      basicAuth:
        username:
          {{- include "dawarich.secretKeyRef" (dict "Key" "metricsUsername" "Value" .Values.metrics.username "Root" .) | nindent 10 }}
        password:
          {{- include "dawarich.secretKeyRef" (dict "Key" "metricsPassword" "Value" .Values.metrics.password "Root" .) | nindent 10 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "dawarich.selectorLabels" . | nindent 6 }}
{{- end }}