{{- $items := list -}}
{{- $items = append $items (dict "Name" "PDNS_API_KEY" "Ref" .Values.powerdns.api.key) -}}
{{- $items = append $items (dict "Name" "PDNS_WEBSERVER_PASSWORD" "Ref" .Values.powerdns.webserver.password) -}}
{{- if ne .Values.powerdns.db.driver "gsqlite3" -}}
{{- $items = append $items (dict "Name" "PDNS_DB_HOST" "Ref" .Values.powerdns.db.host) -}}
{{- $items = append $items (dict "Name" "PDNS_DB_PORT" "Ref" .Values.powerdns.db.port) -}}
{{- $items = append $items (dict "Name" "PDNS_DB_NAME" "Ref" .Values.powerdns.db.name) -}}
{{- $items = append $items (dict "Name" "PDNS_DB_USERNAME" "Ref" .Values.powerdns.db.username) -}}
{{- $items = append $items (dict "Name" "PDNS_DB_PASSWORD" "Ref" .Values.powerdns.db.password) -}}
{{- end -}}
{{- $dataItems := list -}}
{{- range $items -}}
{{- $dataItems = append $dataItems (include "powerdns.secret" (dict "Root" $ "Name" .Name "Ref" .Ref) | trim) -}}
{{- end -}}
{{- $data := join "\n" (compact $dataItems) -}}
{{- if $data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "powerdns.fullname" . }}
  labels:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
type: Opaque
data:
{{ $data | nindent 2 }}
{{- end }}
